# This workflow will compile words/words.md to words/words.html. 
# The content of words/words.html then replaces everything between 
# the article tags in index.html. 
# Any resulting changes will be committed and pushed to master.

name: "Build the website from HackMD"

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "*/5 * * * *"

jobs:
  update_from_hackmd:
    runs-on: ubuntu-18.04
    steps:
      - name: Get the current source from master
        uses: actions/checkout@master
      - name: Get the current content from HackMD
        run: wget -O words/words.md https://hackmd.io/btspyewCRg-15OdTBgEkZQ/download
      - name: Convert markdown to html
        uses: docker://pandoc/core:2.9 # use a docker image that has pandoc pre-installed
        with:
          args: "--from markdown_strict+footnotes words/words.md -o words/words.html"
      - name: Merge html files
        run: cat includes/html_head.html words/words.html includes/html_tail.html > index.html
      - name: Commit and push changes if files have changed
        uses: stefanzweifel/git-auto-commit-action@v4.1.6
        with:
          commit_message: Update index.html from HackMD
          commit_user_name: GitHub Action
          commit_user_email: action@github.com
